diff --git a/Dockerfile b/Dockerfile
index 078921c..af3244e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -48,10 +48,14 @@ RUN go mod download
 
 COPY . .
 
-ARG goflags_arg # default intentionally unset
-ENV GOFLAGS=$goflags_arg
-
-RUN go install -v ./cmd/...
+ARG version_long_arg
+ENV VERSION_LONG=$version_long_arg
+ARG version_short_arg
+ENV VERSION_SHORT=$version_short_arg
+ARG version_git_hash_arg
+ENV VERSION_GIT_HASH=$version_git_hash_arg
+
+RUN go install -tags xversion -ldflags "-X tailscale.com/version.Long=${VERSION_LONG} -X tailscale.com/version.Short=${VERSION_SHORT} -X tailscale.com/version.GitCommit=${VERSION_GIT_HASH}" -v ./cmd/...
 
 FROM alpine:3.11
 RUN apk add --no-cache ca-certificates iptables iproute2
diff --git a/build_docker.sh b/build_docker.sh
index 29dd99f..013989e 100755
--- a/build_docker.sh
+++ b/build_docker.sh
@@ -27,5 +27,4 @@ set -eu
 
 eval $(./version/version.sh)
 
-GOFLAGS='-tags xversion -ldflags '"-X tailscale.com/version.Long=${VERSION_LONG} -X tailscale.com/version.Short=${VERSION_SHORT} -X tailscale.com/version.GitCommit=${VERSION_GIT_HASH}"
-docker build --build-arg goflags_arg="'""${GOFLAGS}""'" -t tailscale:tailscale .
+docker build --build-arg version_long_arg="${VERSION_LONG}" --build-arg version_short_arg="${VERSION_SHORT}" --build-arg version_git_hash_arg="${VERSION_GIT_HASH}" -t tailscale:tailscale .
